/**: # give this to gcu and plane namespaces 
  sensor_topics: # topic specification for each sensor type
    '2': # sensor code
      attribute_order: [serial, temp1, temp2, temp3, pressure, humidity] # strict ordering of attributes for serialization
      attributes: 
        humidity: # attribute key
        - 4 # byte size
        - f # byte type (see python struct)
        pressure:
        - 4
        - f
        serial: # serial is a special code to differential sensor information from the same sensor types.
        - 2
        - i
        temp1:
        - 4
        - f
        temp2:
        - 4
        - f
        temp3:
        - 4
        - f
      msg_type: environ_msgs.msg.Pth # ros msg type
      topic: pth_msg # ros topic msg sensor publishes to
    '3':
      attribute_order: [data]
      attributes:
        data:
        - 64
        - dddddddd
      msg_type: uldaq_msgs.msg.Measurement
      topic: uldaq_measurement
    '1':
      attribute_order: [longitude, latitude, altitude]
      attributes:
        altitude:
        - 4
        - f
        latitude:
        - 4
        - f
        longitude:
        - 4
        - f
      msg_type: sensor_msgs.msg.NavSatFix
      topic: gps_fix
    '4':
      attribute_order: [wind_angle, wind_speed]
      attributes:
        wind_angle:
        - 4
        - f
        wind_speed:
        - 4
        - f
      msg_type: environ_msgs.msg.NMEA_MWV
      sensor_code: '4'
      topic: wind_speed
    '5':
      attribute_order: [temp]
      attributes:
        temp:
        - 4
        - f
      msg_type: environ_msgs.msg.NMEA_XDR
      topic: air_temp
  gcu_addr: 13A20041D17945
  time_topic: gps_time
