/**: # give this to gcu and plane namespaces 
    gsu:
        ros__parameters:
            gcu_addr: 13A20041D17945
            time_topic: gps_time
    plane:
        ros__parameters:
            gcu_addr: 13A20041D17945
            time_topic: gps_time
